src/Components/AppShell/NavBar.tsx
src/Components/AppShell/SideBar.tsx
src/Components/Auth/useAuth.tsx
src/Components/Input/TextAreaInput.tsx
src/Components/Map/Layer.tsx
src/Components/Map/Subcomponents/Controls/SearchControl.tsx
src/Components/Map/Subcomponents/ItemPopupComponents/HeaderView.tsx
src/Components/Map/Subcomponents/ItemPopupComponents/PopupButton.tsx
src/Components/Map/Subcomponents/ItemViewPopup.tsx
src/Components/Map/Tags.tsx
src/Components/Map/UtopiaMapInner.tsx
src/Components/Map/hooks/useFilter.tsx
src/Components/Map/hooks/useSelectPosition.tsx
src/Components/Profile/Subcomponents/ContactInfo.tsx
src/Components/Profile/Templates/OnepagerView.tsx
src/Components/Profile/Templates/TabsForm.tsx
src/Components/Profile/Templates/TabsView.tsx
src/Components/Profile/itemFunctions.ts
src/Components/Templates/AttestationForm.tsx
src/Components/Templates/ItemCard.tsx
src/Components/Templates/MoonCalendar.tsx
src/Utils/GetValue.ts
src/Utils/Moon.ts
src/Utils/RandomColor.ts
src/Utils/TimeAgo.ts

Changes a lot of `let` / `var`  to `const`
- None

fix(other): lint autofixes

---

.github/workflows/test.build.yml

feat(workflow): new build workflow

---

.eslintignore

fix(other): lint ignore

---

src/Components/Map/hooks/usePermissions.tsx

fix(other): permission fix

---

package-lock.json
package.json
src/Components/Map/hooks/usePermissions.tsx

fix(other): final permission fix

---

.eslintrc.js
package-lock.json
package.json
postcss.config.js
src/Components/AppShell/hooks/useAssets.tsx
src/Components/Auth/useAuth.tsx
src/Components/Gaming/hooks/useQuests.tsx
src/Components/Input/Autocomplete.tsx
src/Components/Input/ComboBoxInput.tsx
src/Components/Input/SelectBox.tsx
src/Components/Input/TextAreaInput.tsx
src/Components/Input/TextInput.tsx
src/Components/Map/Subcomponents/ItemPopupComponents/PopupStartEndInput.tsx
src/Components/Map/Subcomponents/ItemPopupComponents/TextView.tsx
src/Components/Map/hooks/useFilter.tsx
src/Components/Map/hooks/useItems.tsx
src/Components/Map/hooks/useLayers.tsx
src/Components/Map/hooks/useLeafletRefs.tsx
src/Components/Map/hooks/usePermissions.tsx
src/Components/Map/hooks/useTags.tsx
src/Components/Profile/Templates/TabsForm.tsx
src/Components/Profile/Templates/TabsView.tsx
src/Utils/ReplaceURLs.ts
src/types.ts
tailwind.config.js

fix(other): lint comments

---

package.json

fix(other): fix wrong license in package.json

---

package-lock.json
package.json
src/Components/Map/Subcomponents/ItemFormPopup.tsx
src/Components/Profile/Subcomponents/ContactInfoForm.tsx
src/Components/Profile/Subcomponents/GroupSubHeaderView.tsx
src/Components/Profile/Subcomponents/SocialShareBar.tsx
src/Components/Profile/Subcomponents/SocialShareButton.tsx
src/Components/Profile/Templates/OnepagerView.tsx

fix(other): advanced Social Share Buttons

---

src/Utils/ReplaceURLs.ts

fix(other): updated regex for mail detection

---

.eslintrc.js
src/Components/Auth/SetNewPasswordPage.tsx
src/Components/Map/Subcomponents/Controls/SearchControl.tsx
src/Components/Map/Subcomponents/ItemFormPopup.tsx
src/Components/Map/UtopiaMapInner.tsx
src/Components/Profile/ProfileView.tsx
src/Components/Profile/Subcomponents/ContactInfoView.tsx
src/Components/Profile/Subcomponents/GroupSubheaderForm.tsx
src/Components/Profile/Templates/FlexView.tsx
src/Components/Templates/MarketView.tsx
src/Utils/ReverseGeocoder.ts

lint console
This PR disallows console.logs, but ignores all existing console logs. It might be wise to reevaluate this strategy - maybe removing the console.log calls would be better. The selected solution optimizes for the least impact on the code.
- None

feat(other): lint console

---

README.md

fix(other): update README.md

---

.eslintrc.js
package-lock.json
package.json
src/Components/AppShell/ContextWrapper.tsx
src/Components/Auth/useAuth.tsx
src/Components/Map/Subcomponents/Controls/SearchControl.tsx
src/Components/Map/Subcomponents/ItemFormPopup.tsx
src/Components/Map/Subcomponents/ItemViewPopup.tsx
src/Components/Map/hooks/useSelectPosition.tsx
src/Components/Profile/itemFunctions.ts
src/Components/Templates/OverlayItemsIndexPage.tsx
src/Utils/ReverseGeocoder.ts

lint catchall
Installs no-catch-all linter and ignores all existing errors - a future reevaluation of those would be beneficial.
- None

feat(other): lint catchall

---

package-lock.json
package.json

fix(other): fix vulnerability

---

package-lock.json
package.json
src/Components/Input/TextInput.tsx
src/Components/Map/Subcomponents/ItemPopupComponents/HeaderView.tsx
src/Components/Map/Subcomponents/ItemPopupComponents/TextView.tsx
src/Components/Profile/ProfileForm.tsx
src/Components/Profile/Subcomponents/ContactInfoForm.tsx
src/Components/Profile/Subcomponents/FormHeader.tsx
src/Components/Profile/Subcomponents/GroupSubheaderForm.tsx

We had some profile form issues reported from the community

fix(other): fix some profile issues

---

README.md

fix(other): update readme

---

.github/workflows/test.lint.pr.yml

refactor(workflow): update test.lint.pr.yml

---

CODE_OF_CONDUCT.md

Creates a CODE_OF_CONDUCT.md to define what is undesirable behavior in meetings and how we deal with it

docs(docu): create CODE_OF_CONDUCT.md

---

src/Components/AppShell/NavBar.tsx
src/Components/Gaming/Modal.tsx
src/Components/Gaming/Quests.tsx
src/Components/Map/Subcomponents/ItemFormPopup.tsx
src/Components/Profile/ProfileForm.tsx
src/Components/Profile/Subcomponents/ContactInfoView.tsx
src/Components/Profile/Templates/OnepagerView.tsx
src/Components/Profile/Templates/TabsView.tsx
src/Components/Templates/AttestationForm.tsx
src/Components/Templates/DateUserInfo.tsx
src/Components/Templates/OverlayItemsIndexPage.tsx
src/index.tsx
types/Item.d.ts
types/UserItem.d.ts

fix(other): make NavBar typesafe

---

examples/basic-map/README.md

docs(docu): update README.md

---

CONTRIBUTING.md

I added some information how to setup a local dev environment

docs(docu): update CONTRIBUTING.md

---

README.md

docs(docu): link contribution guide to README.md

---

examples/2-static-layers/package-lock.json
examples/2-static-layers/package.json
src/Components/Map/Layer.tsx
src/Components/Map/UtopiaMap.tsx
src/Components/Map/UtopiaMapInner.tsx
src/Utils/ContainsUUID.ts

fix(source): cleanup maps and layers

---

src/Utils/ContainsUUID.ts

fix(source): removed some logging

---

src/index.tsx

fix(source): remove useAuth from export

---

.github/workflows/test.build.yml

I have extended the build workflow so that the build is tested with the examaples

fix(workflow): update test.build.yml

---

package.json

update-command
implement update command for package updates
`npm run update`
- None

feat(other): update-command

---

.eslintrc.js
src/Components/Map/Subcomponents/Controls/LocateControl.tsx
src/Components/Map/UtopiaMap.tsx
src/Components/Map/UtopiaMapInner.tsx
src/Components/Profile/Subcomponents/AvatarWidget.tsx
src/Components/Profile/Subcomponents/ColorPicker.tsx
src/index.tsx

allow import of css like `import './style.css' `

fix(workflow): disabled no-unassigned-import for css

---

.github/workflows/test.lint.examples.yml

lint examples
have a workflow for each example to lint according to local lint rules
Note: As the examples are setup as independent project, it makes sense to test them according to their respectively defined eslint rules. They are as of now not comparable with the lint rules defined for the main project.
See:
- https://github.com/utopia-os/utopia-ui/actions/runs/13067955645/job/36463465414?pr=86
- https://github.com/utopia-os/utopia-ui/actions/runs/13067955645/job/36463465236?pr=86
- releates #85

feat(workflow): lint examples

---

package-lock.json
package.json

update typescript to latest version
- None

feat(other): update-typescript

---

.github/workflows/test.unit.yml

feat(workflow): unit tests

---

.github/workflows/test.docs.yml
package-lock.json
package.json
scripts/docs-coverage.sh

test documentation coverage
make it possible to require certain amount of documented code
- None

feat(workflow): test documentation coverage

---

package-lock.json
package.json
src/Components/Map/Subcomponents/ItemPopupComponents/HeaderView.tsx

show a placeholder while avatar image is loading

feat(source): add avatar placeholder

---

.eslintignore

fix(workflow): add /coverage to .eslintignore

---

package-lock.json
package.json
src/Components/Profile/Templates/TabsForm.tsx

fix(source): contact not mandotory in tabview

---

package.json

docs: include version in the title
Include the version according to the package.json in the title of docs page.
- None

feat(docu): include version in the title

---

rollup.config.js

fix delayed build
We noticed that the build was outdated and lagged behind 1 build.
Reason for this is rollup and its second config.
Solved by
https://github.com/rollup/rollup/issues/1666#issuecomment-1163091988
This could cause problems when types change
- fixes #146

fix(other): delayed build

---

src/Components/AppShell/Content.tsx
src/Components/AppShell/ContextWrapper.tsx
src/Components/Gaming/hooks/useQuests.tsx
src/Components/Input/SelectBox.tsx
src/Components/Input/TextAreaInput.tsx
src/Components/Input/TextInput.tsx
src/Components/Input/__snapshots__/TextInput.spec.tsx.snap
src/Components/Map/hooks/useDebounce.tsx
src/Components/Map/hooks/useLayers.tsx
src/Components/Map/hooks/usePermissions.tsx
src/types/UserItem.d.ts
vite.config.ts

refactor(source): define more types

---

src/Components/Input/TextAreaInput.spec.tsx
src/Components/Input/TextAreaInput.tsx
src/Components/Input/__snapshots__/TextAreaInput.spec.tsx.snap
vite.config.ts

Unit Test for the `TextAreaInput` component
- None

feat(source): test text area input

---

src/Components/Input/ComboBoxInput.spec.tsx
src/Components/Input/__snapshots__/ComboBoxInput.spec.tsx.snap

feat(source): unit test for combo box component

---

.github/workflows/test.unit.yml
vite.config.ts

unit tests workflow not running properly
The pedicate-quantifier every seem not to mach properly
Problematic worklfow:
https://github.com/utopia-os/utopia-ui/actions/runs/13639312728/job/38125326624
The PR(https://github.com/utopia-os/utopia-ui/pull/172) did not execute, but tsx files were changed.
https://github.com/utopia-os/utopia-ui/actions/runs/13639281764/job/38125219264
- relates https://github.com/utopia-os/utopia-ui/pull/118

fix(workflow): unit tests workflow not running properly

---

src/Components/Map/Subcomponents/ItemFormPopup.tsx

fix(source): fix bug in ItemFormPopup

---

README.md

refactor(docu): add browserstack hint to readme.md

---

package.json

Sometimes code changes require updating the snapshots to adapt the unit tests to the changes.
This can be automatically performed by adding the `-u` parameter to the unit test commad.
In #196 we had such a case.
To fix the unit tests that failed due to snapshots that were not yet adapted to the changes, [this parameter has been used](https://github.com/utopia-os/utopia-ui/pull/196/commits/6af8a4f70694f47bfb2b16f003312c5fa4789cae).

feat(other): add unit test update script to package.json

---

examples/README.md

fix(docu): extending examples

---

src/Components/Profile/ItemFunctions.spec.tsx
vite.config.ts

test(source): linkItem() tested

---

package-lock.json
package.json
src/assets/css/leaflet.css

the radius of the popup tip was effected by the selected theme
but it should always be pointed without radius

fix(source): fix popup tip
